### ISSUE TITLE
teleport runes

### ISSUE THREAD

**Issue by xenoterracide** [AlexHaible/BetterBags-Teleports#1]
playing classic. As a mage can we put the teleport/portal runes in the same category as the other teleports. I know they aren't "actionable" themselves. They do however corelate to me teleporting to the capitals.

**Comment by xenoterracide** [comment]
I updated this morning, still seems that the teleport stone is in reagents, is there some further action I need to do aside from updating the addon?

![2024-07-17 10_15_03-Window](https://github.com/user-attachments/assets/424160b8-312d-439b-bd44-526ec3344bef)

**Comment by AlexHaible** [comment]
Yes, go toggle it in the plugin settings. If you click the bag button, then click options, you should see a menu option called "Plugins". In there you'll find Teleporters, and it's single option that'll put the 2 reagents into the category.
