### ISSUE TITLE
Trouble with Themes plugin

### ISSUE THREAD

**Issue by cwwood0322** [AlexHaible/BetterBags-Teleports#2]
With the latest updates on Betterbags, the themes plugin not working correctly, the theme still works on the bags but without the clickable icon on the upper left corner. Also, when you open the bank there is no background with it, you just see the contents of the bank.

**Comment by AlexHaible** [comment]
Fixed with this commit: https://github.com/AlexHaible/BetterBags-Themes/commit/4350de795f00d546064f583e30dee78dc86068e1

Also, Themes has it's own issue tracker. This one is for Teleporters. ;)
