### ISSUE TITLE
Feature Reuest: Add support for Betterbags-Priority

### ISSUE THREAD

**Issue by Tayedaen** [AlexHaible/BetterBags-Teleports#3]
Hi,

first thank you for this great plugin for Betterbags!
Now my request: Could you please add support for Betterbags-Priority?
https://www.curseforge.com/wow/addons/betterbags-priority

This would make it possible to move the Teleports section to whatever place we want to.
Thank you in advance for looking into it.

BR

**Comment by AlexHaible** [comment]
Priority won't decide where the category goes. Just if an item should be grabbed by it or not.

You should give the pinning system a look. That'll allow you to move the category around so long as it's amongst other pinned categories.

**Comment by Tayedaen** [comment]
Thank you for the explanation, pinning did the job. 
Thank you !
